### ISSUE TITLE
Two flash notices shown on user update.

### ISSUE THREAD

**Issue by jamsterwes** [Ahnaf-Abid-Hossain/association_of_baptist_students#32]
![image](https://github.com/Ahnaf-Abid-Hossain/association_of_baptist_students/assets/10291902/feaf3ca4-7fe3-477a-8c6f-ab16cf504797)

Both the blue notice (above navbar) and green notice (below navbar) shown.

**Comment by jamsterwes** [comment]
(edited so i don't dox my phone # to a public repo 😐)

**Comment by parkerjacob37** [comment]
Bug fixed, merged to dev in PR #37
